name: 'Test Docker Compose'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run compose
      run: |
        # change image to localbuild using yq
        yq eval 'del(.services.server.image)' -i docker-compose.yml
        yq eval '.services.server.build.context = "../../../"' -i docker-compose.yml
        yq eval '.services.server.build.dockerfile = "./packages/twenty-docker/prod/twenty/Dockerfile"' -i docker-compose.yml

        yq eval 'del(.services.db.image)' -i docker-compose.yml
        yq eval '.services.db.build.context = "../../../"' -i docker-compose.yml
        yq eval '.services.db.build.dockerfile = "./packages/twenty-docker/prod/twenty-postgres/Dockerfile"' -i docker-compose.yml

        docker-compose up -d

        docker-compose logs &
        pid = $!

        count=0
        while ! curl -s http://localhost:3000;
            do sleep 1;
            count=$((count+1));
            if [ $count -gt 300 ]; then
                echo "Failed to start server"
                exit 1
            fi
        done
      working-directory: ./packages/twenty-docker/prod/
