name: CI-Vale
on: 
  pull_request:
  workflow_dispatch:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          vale_flags: '--minAlertLevel=error'
          reporter: github-pr-check
          filter_mode: nofilter
          token: ${{secrets.VALE_GITHUB_TOKEN}}