name: CI-Vale
on: workflow_dispatch
  # pull_request:
  #   paths:
  #      - docs/**   



jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: docs/**
          fail_on_error: false