name: CI-Vale
on: workflow_dispatch
  # pull_request:
  #   paths:
  #      - docs/**   

with:
  files: docs/**
  fail_on_error: false

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog